// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: pkg/trip/pb/trip.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTripRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PickupLatitude   float64                `protobuf:"fixed64,2,opt,name=pickup_latitude,json=pickupLatitude,proto3" json:"pickup_latitude,omitempty"`
	PickupLongitude  float64                `protobuf:"fixed64,3,opt,name=pickup_longitude,json=pickupLongitude,proto3" json:"pickup_longitude,omitempty"`
	DropoffLatitude  float64                `protobuf:"fixed64,4,opt,name=dropoff_latitude,json=dropoffLatitude,proto3" json:"dropoff_latitude,omitempty"`
	DropoffLongitude float64                `protobuf:"fixed64,5,opt,name=dropoff_longitude,json=dropoffLongitude,proto3" json:"dropoff_longitude,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateTripRequest) Reset() {
	*x = CreateTripRequest{}
	mi := &file_pkg_trip_pb_trip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripRequest) ProtoMessage() {}

func (x *CreateTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_trip_pb_trip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripRequest.ProtoReflect.Descriptor instead.
func (*CreateTripRequest) Descriptor() ([]byte, []int) {
	return file_pkg_trip_pb_trip_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTripRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTripRequest) GetPickupLatitude() float64 {
	if x != nil {
		return x.PickupLatitude
	}
	return 0
}

func (x *CreateTripRequest) GetPickupLongitude() float64 {
	if x != nil {
		return x.PickupLongitude
	}
	return 0
}

func (x *CreateTripRequest) GetDropoffLatitude() float64 {
	if x != nil {
		return x.DropoffLatitude
	}
	return 0
}

func (x *CreateTripRequest) GetDropoffLongitude() float64 {
	if x != nil {
		return x.DropoffLongitude
	}
	return 0
}

type CreateTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DriverId      int64                  `protobuf:"varint,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	TripId        int64                  `protobuf:"varint,4,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTripResponse) Reset() {
	*x = CreateTripResponse{}
	mi := &file_pkg_trip_pb_trip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripResponse) ProtoMessage() {}

func (x *CreateTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_trip_pb_trip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripResponse.ProtoReflect.Descriptor instead.
func (*CreateTripResponse) Descriptor() ([]byte, []int) {
	return file_pkg_trip_pb_trip_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTripResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateTripResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateTripResponse) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *CreateTripResponse) GetTripId() int64 {
	if x != nil {
		return x.TripId
	}
	return 0
}

type EstimateTripFareRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PickupLatitude   float64                `protobuf:"fixed64,1,opt,name=pickup_latitude,json=pickupLatitude,proto3" json:"pickup_latitude,omitempty"`
	PickupLongitude  float64                `protobuf:"fixed64,2,opt,name=pickup_longitude,json=pickupLongitude,proto3" json:"pickup_longitude,omitempty"`
	DropoffLatitude  float64                `protobuf:"fixed64,3,opt,name=dropoff_latitude,json=dropoffLatitude,proto3" json:"dropoff_latitude,omitempty"`
	DropoffLongitude float64                `protobuf:"fixed64,4,opt,name=dropoff_longitude,json=dropoffLongitude,proto3" json:"dropoff_longitude,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EstimateTripFareRequest) Reset() {
	*x = EstimateTripFareRequest{}
	mi := &file_pkg_trip_pb_trip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateTripFareRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateTripFareRequest) ProtoMessage() {}

func (x *EstimateTripFareRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_trip_pb_trip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateTripFareRequest.ProtoReflect.Descriptor instead.
func (*EstimateTripFareRequest) Descriptor() ([]byte, []int) {
	return file_pkg_trip_pb_trip_proto_rawDescGZIP(), []int{2}
}

func (x *EstimateTripFareRequest) GetPickupLatitude() float64 {
	if x != nil {
		return x.PickupLatitude
	}
	return 0
}

func (x *EstimateTripFareRequest) GetPickupLongitude() float64 {
	if x != nil {
		return x.PickupLongitude
	}
	return 0
}

func (x *EstimateTripFareRequest) GetDropoffLatitude() float64 {
	if x != nil {
		return x.DropoffLatitude
	}
	return 0
}

func (x *EstimateTripFareRequest) GetDropoffLongitude() float64 {
	if x != nil {
		return x.DropoffLongitude
	}
	return 0
}

type EstimateTripFareResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Distance         float64                `protobuf:"fixed64,1,opt,name=distance,proto3" json:"distance,omitempty"`
	EstimateTripFare int64                  `protobuf:"varint,2,opt,name=estimate_trip_fare,json=estimateTripFare,proto3" json:"estimate_trip_fare,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EstimateTripFareResponse) Reset() {
	*x = EstimateTripFareResponse{}
	mi := &file_pkg_trip_pb_trip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateTripFareResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateTripFareResponse) ProtoMessage() {}

func (x *EstimateTripFareResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_trip_pb_trip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateTripFareResponse.ProtoReflect.Descriptor instead.
func (*EstimateTripFareResponse) Descriptor() ([]byte, []int) {
	return file_pkg_trip_pb_trip_proto_rawDescGZIP(), []int{3}
}

func (x *EstimateTripFareResponse) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *EstimateTripFareResponse) GetEstimateTripFare() int64 {
	if x != nil {
		return x.EstimateTripFare
	}
	return 0
}

var File_pkg_trip_pb_trip_proto protoreflect.FileDescriptor

const file_pkg_trip_pb_trip_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/trip/pb/trip.proto\x12\x04trip\"\xd8\x01\n" +
	"\x11CreateTripRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0fpickup_latitude\x18\x02 \x01(\x01R\x0epickupLatitude\x12)\n" +
	"\x10pickup_longitude\x18\x03 \x01(\x01R\x0fpickupLongitude\x12)\n" +
	"\x10dropoff_latitude\x18\x04 \x01(\x01R\x0fdropoffLatitude\x12+\n" +
	"\x11dropoff_longitude\x18\x05 \x01(\x01R\x10dropoffLongitude\"|\n" +
	"\x12CreateTripResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\x03R\bdriverId\x12\x17\n" +
	"\atrip_id\x18\x04 \x01(\x03R\x06tripId\"\xc5\x01\n" +
	"\x17EstimateTripFareRequest\x12'\n" +
	"\x0fpickup_latitude\x18\x01 \x01(\x01R\x0epickupLatitude\x12)\n" +
	"\x10pickup_longitude\x18\x02 \x01(\x01R\x0fpickupLongitude\x12)\n" +
	"\x10dropoff_latitude\x18\x03 \x01(\x01R\x0fdropoffLatitude\x12+\n" +
	"\x11dropoff_longitude\x18\x04 \x01(\x01R\x10dropoffLongitude\"d\n" +
	"\x18EstimateTripFareResponse\x12\x1a\n" +
	"\bdistance\x18\x01 \x01(\x01R\bdistance\x12,\n" +
	"\x12estimate_trip_fare\x18\x02 \x01(\x03R\x10estimateTripFare2\xa1\x01\n" +
	"\vTripService\x12?\n" +
	"\n" +
	"CreateTrip\x12\x17.trip.CreateTripRequest\x1a\x18.trip.CreateTripResponse\x12Q\n" +
	"\x10EstimateTripFare\x12\x1d.trip.EstimateTripFareRequest\x1a\x1e.trip.EstimateTripFareResponseB\n" +
	"Z\b./pkg/pbb\x06proto3"

var (
	file_pkg_trip_pb_trip_proto_rawDescOnce sync.Once
	file_pkg_trip_pb_trip_proto_rawDescData []byte
)

func file_pkg_trip_pb_trip_proto_rawDescGZIP() []byte {
	file_pkg_trip_pb_trip_proto_rawDescOnce.Do(func() {
		file_pkg_trip_pb_trip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_trip_pb_trip_proto_rawDesc), len(file_pkg_trip_pb_trip_proto_rawDesc)))
	})
	return file_pkg_trip_pb_trip_proto_rawDescData
}

var file_pkg_trip_pb_trip_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_trip_pb_trip_proto_goTypes = []any{
	(*CreateTripRequest)(nil),        // 0: trip.CreateTripRequest
	(*CreateTripResponse)(nil),       // 1: trip.CreateTripResponse
	(*EstimateTripFareRequest)(nil),  // 2: trip.EstimateTripFareRequest
	(*EstimateTripFareResponse)(nil), // 3: trip.EstimateTripFareResponse
}
var file_pkg_trip_pb_trip_proto_depIdxs = []int32{
	0, // 0: trip.TripService.CreateTrip:input_type -> trip.CreateTripRequest
	2, // 1: trip.TripService.EstimateTripFare:input_type -> trip.EstimateTripFareRequest
	1, // 2: trip.TripService.CreateTrip:output_type -> trip.CreateTripResponse
	3, // 3: trip.TripService.EstimateTripFare:output_type -> trip.EstimateTripFareResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_trip_pb_trip_proto_init() }
func file_pkg_trip_pb_trip_proto_init() {
	if File_pkg_trip_pb_trip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_trip_pb_trip_proto_rawDesc), len(file_pkg_trip_pb_trip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_trip_pb_trip_proto_goTypes,
		DependencyIndexes: file_pkg_trip_pb_trip_proto_depIdxs,
		MessageInfos:      file_pkg_trip_pb_trip_proto_msgTypes,
	}.Build()
	File_pkg_trip_pb_trip_proto = out.File
	file_pkg_trip_pb_trip_proto_goTypes = nil
	file_pkg_trip_pb_trip_proto_depIdxs = nil
}
