// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: pkg/driver/pb/driver.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vehicle       string                 `protobuf:"bytes,2,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	LicenseNumber string                 `protobuf:"bytes,6,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDriverRequest) Reset() {
	*x = CreateDriverRequest{}
	mi := &file_pkg_driver_pb_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverRequest) ProtoMessage() {}

func (x *CreateDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_driver_pb_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverRequest.ProtoReflect.Descriptor instead.
func (*CreateDriverRequest) Descriptor() ([]byte, []int) {
	return file_pkg_driver_pb_driver_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDriverRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDriverRequest) GetVehicle() string {
	if x != nil {
		return x.Vehicle
	}
	return ""
}

func (x *CreateDriverRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateDriverRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateDriverRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateDriverRequest) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

type CreateDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Vehicle       string                 `protobuf:"bytes,5,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDriverResponse) Reset() {
	*x = CreateDriverResponse{}
	mi := &file_pkg_driver_pb_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverResponse) ProtoMessage() {}

func (x *CreateDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_driver_pb_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverResponse.ProtoReflect.Descriptor instead.
func (*CreateDriverResponse) Descriptor() ([]byte, []int) {
	return file_pkg_driver_pb_driver_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDriverResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateDriverResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateDriverResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateDriverResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDriverResponse) GetVehicle() string {
	if x != nil {
		return x.Vehicle
	}
	return ""
}

func (x *CreateDriverResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpdateDriverLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverLocationRequest) Reset() {
	*x = UpdateDriverLocationRequest{}
	mi := &file_pkg_driver_pb_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverLocationRequest) ProtoMessage() {}

func (x *UpdateDriverLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_driver_pb_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateDriverLocationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_driver_pb_driver_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDriverLocationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDriverLocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateDriverLocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type UpdateDriverLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverLocationResponse) Reset() {
	*x = UpdateDriverLocationResponse{}
	mi := &file_pkg_driver_pb_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverLocationResponse) ProtoMessage() {}

func (x *UpdateDriverLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_driver_pb_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateDriverLocationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_driver_pb_driver_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDriverLocationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateDriverLocationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_driver_pb_driver_proto protoreflect.FileDescriptor

const file_pkg_driver_pb_driver_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/driver/pb/driver.proto\x12\x06driver\"\xb2\x01\n" +
	"\x13CreateDriverRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\avehicle\x18\x02 \x01(\tR\avehicle\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12%\n" +
	"\x0elicense_number\x18\x06 \x01(\tR\rlicenseNumber\"\x98\x01\n" +
	"\x14CreateDriverResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\avehicle\x18\x05 \x01(\tR\avehicle\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\"g\n" +
	"\x1bUpdateDriverLocationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\"P\n" +
	"\x1cUpdateDriverLocationResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xbd\x01\n" +
	"\rDriverService\x12I\n" +
	"\fCreateDriver\x12\x1b.driver.CreateDriverRequest\x1a\x1c.driver.CreateDriverResponse\x12a\n" +
	"\x14UpdateDriverLocation\x12#.driver.UpdateDriverLocationRequest\x1a$.driver.UpdateDriverLocationResponseB\n" +
	"Z\b./pkg/pbb\x06proto3"

var (
	file_pkg_driver_pb_driver_proto_rawDescOnce sync.Once
	file_pkg_driver_pb_driver_proto_rawDescData []byte
)

func file_pkg_driver_pb_driver_proto_rawDescGZIP() []byte {
	file_pkg_driver_pb_driver_proto_rawDescOnce.Do(func() {
		file_pkg_driver_pb_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_driver_pb_driver_proto_rawDesc), len(file_pkg_driver_pb_driver_proto_rawDesc)))
	})
	return file_pkg_driver_pb_driver_proto_rawDescData
}

var file_pkg_driver_pb_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_driver_pb_driver_proto_goTypes = []any{
	(*CreateDriverRequest)(nil),          // 0: driver.CreateDriverRequest
	(*CreateDriverResponse)(nil),         // 1: driver.CreateDriverResponse
	(*UpdateDriverLocationRequest)(nil),  // 2: driver.UpdateDriverLocationRequest
	(*UpdateDriverLocationResponse)(nil), // 3: driver.UpdateDriverLocationResponse
}
var file_pkg_driver_pb_driver_proto_depIdxs = []int32{
	0, // 0: driver.DriverService.CreateDriver:input_type -> driver.CreateDriverRequest
	2, // 1: driver.DriverService.UpdateDriverLocation:input_type -> driver.UpdateDriverLocationRequest
	1, // 2: driver.DriverService.CreateDriver:output_type -> driver.CreateDriverResponse
	3, // 3: driver.DriverService.UpdateDriverLocation:output_type -> driver.UpdateDriverLocationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_driver_pb_driver_proto_init() }
func file_pkg_driver_pb_driver_proto_init() {
	if File_pkg_driver_pb_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_driver_pb_driver_proto_rawDesc), len(file_pkg_driver_pb_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_driver_pb_driver_proto_goTypes,
		DependencyIndexes: file_pkg_driver_pb_driver_proto_depIdxs,
		MessageInfos:      file_pkg_driver_pb_driver_proto_msgTypes,
	}.Build()
	File_pkg_driver_pb_driver_proto = out.File
	file_pkg_driver_pb_driver_proto_goTypes = nil
	file_pkg_driver_pb_driver_proto_depIdxs = nil
}
