// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: pkg/pb/driver.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vehicle       string                 `protobuf:"bytes,2,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	LicenseNumber string                 `protobuf:"bytes,6,opt,name=license_number,json=licenseNumber,proto3" json:"license_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDriverRequest) Reset() {
	*x = CreateDriverRequest{}
	mi := &file_pkg_pb_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverRequest) ProtoMessage() {}

func (x *CreateDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverRequest.ProtoReflect.Descriptor instead.
func (*CreateDriverRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_driver_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDriverRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDriverRequest) GetVehicle() string {
	if x != nil {
		return x.Vehicle
	}
	return ""
}

func (x *CreateDriverRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateDriverRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateDriverRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateDriverRequest) GetLicenseNumber() string {
	if x != nil {
		return x.LicenseNumber
	}
	return ""
}

type CreateDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Id            int64                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Vehicle       string                 `protobuf:"bytes,5,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDriverResponse) Reset() {
	*x = CreateDriverResponse{}
	mi := &file_pkg_pb_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverResponse) ProtoMessage() {}

func (x *CreateDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverResponse.ProtoReflect.Descriptor instead.
func (*CreateDriverResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_driver_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDriverResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateDriverResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateDriverResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateDriverResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDriverResponse) GetVehicle() string {
	if x != nil {
		return x.Vehicle
	}
	return ""
}

func (x *CreateDriverResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpdateDriverLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverLocationRequest) Reset() {
	*x = UpdateDriverLocationRequest{}
	mi := &file_pkg_pb_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverLocationRequest) ProtoMessage() {}

func (x *UpdateDriverLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateDriverLocationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_driver_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDriverLocationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDriverLocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateDriverLocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type UpdateDriverLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverLocationResponse) Reset() {
	*x = UpdateDriverLocationResponse{}
	mi := &file_pkg_pb_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverLocationResponse) ProtoMessage() {}

func (x *UpdateDriverLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateDriverLocationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_driver_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDriverLocationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateDriverLocationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAvailableDriversNearUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	MaxDriver     int32                  `protobuf:"varint,3,opt,name=max_driver,json=maxDriver,proto3" json:"max_driver,omitempty"`
	Radius        int32                  `protobuf:"varint,4,opt,name=radius,proto3" json:"radius,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableDriversNearUserRequest) Reset() {
	*x = GetAvailableDriversNearUserRequest{}
	mi := &file_pkg_pb_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableDriversNearUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableDriversNearUserRequest) ProtoMessage() {}

func (x *GetAvailableDriversNearUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableDriversNearUserRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableDriversNearUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_driver_proto_rawDescGZIP(), []int{4}
}

func (x *GetAvailableDriversNearUserRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetAvailableDriversNearUserRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetAvailableDriversNearUserRequest) GetMaxDriver() int32 {
	if x != nil {
		return x.MaxDriver
	}
	return 0
}

func (x *GetAvailableDriversNearUserRequest) GetRadius() int32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

type GetAvailableDriversNearUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Drivers       []int64                `protobuf:"varint,2,rep,packed,name=drivers,proto3" json:"drivers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableDriversNearUserResponse) Reset() {
	*x = GetAvailableDriversNearUserResponse{}
	mi := &file_pkg_pb_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableDriversNearUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableDriversNearUserResponse) ProtoMessage() {}

func (x *GetAvailableDriversNearUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableDriversNearUserResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableDriversNearUserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_driver_proto_rawDescGZIP(), []int{5}
}

func (x *GetAvailableDriversNearUserResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetAvailableDriversNearUserResponse) GetDrivers() []int64 {
	if x != nil {
		return x.Drivers
	}
	return nil
}

type SendNotificationToDriverRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DriverId         int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	PickupLatitude   float64                `protobuf:"fixed64,2,opt,name=pickup_latitude,json=pickupLatitude,proto3" json:"pickup_latitude,omitempty"`
	PickupLongitude  float64                `protobuf:"fixed64,3,opt,name=pickup_longitude,json=pickupLongitude,proto3" json:"pickup_longitude,omitempty"`
	DropoffLatitude  float64                `protobuf:"fixed64,4,opt,name=dropoff_latitude,json=dropoffLatitude,proto3" json:"dropoff_latitude,omitempty"`
	DropoffLongitude float64                `protobuf:"fixed64,5,opt,name=dropoff_longitude,json=dropoffLongitude,proto3" json:"dropoff_longitude,omitempty"`
	Distance         float64                `protobuf:"fixed64,6,opt,name=distance,proto3" json:"distance,omitempty"`
	TripFare         int64                  `protobuf:"varint,7,opt,name=trip_fare,json=tripFare,proto3" json:"trip_fare,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendNotificationToDriverRequest) Reset() {
	*x = SendNotificationToDriverRequest{}
	mi := &file_pkg_pb_driver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationToDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationToDriverRequest) ProtoMessage() {}

func (x *SendNotificationToDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_driver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationToDriverRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationToDriverRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_driver_proto_rawDescGZIP(), []int{6}
}

func (x *SendNotificationToDriverRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *SendNotificationToDriverRequest) GetPickupLatitude() float64 {
	if x != nil {
		return x.PickupLatitude
	}
	return 0
}

func (x *SendNotificationToDriverRequest) GetPickupLongitude() float64 {
	if x != nil {
		return x.PickupLongitude
	}
	return 0
}

func (x *SendNotificationToDriverRequest) GetDropoffLatitude() float64 {
	if x != nil {
		return x.DropoffLatitude
	}
	return 0
}

func (x *SendNotificationToDriverRequest) GetDropoffLongitude() float64 {
	if x != nil {
		return x.DropoffLongitude
	}
	return 0
}

func (x *SendNotificationToDriverRequest) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *SendNotificationToDriverRequest) GetTripFare() int64 {
	if x != nil {
		return x.TripFare
	}
	return 0
}

type SendNotificationToDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationToDriverResponse) Reset() {
	*x = SendNotificationToDriverResponse{}
	mi := &file_pkg_pb_driver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationToDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationToDriverResponse) ProtoMessage() {}

func (x *SendNotificationToDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_driver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationToDriverResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationToDriverResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_driver_proto_rawDescGZIP(), []int{7}
}

func (x *SendNotificationToDriverResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SendNotificationToDriverResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResponseToTripServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        int64                  `protobuf:"varint,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	DriverId      int64                  `protobuf:"varint,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Accept        bool                   `protobuf:"varint,3,opt,name=accept,proto3" json:"accept,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseToTripServiceRequest) Reset() {
	*x = ResponseToTripServiceRequest{}
	mi := &file_pkg_pb_driver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseToTripServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseToTripServiceRequest) ProtoMessage() {}

func (x *ResponseToTripServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_driver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseToTripServiceRequest.ProtoReflect.Descriptor instead.
func (*ResponseToTripServiceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_driver_proto_rawDescGZIP(), []int{8}
}

func (x *ResponseToTripServiceRequest) GetTripId() int64 {
	if x != nil {
		return x.TripId
	}
	return 0
}

func (x *ResponseToTripServiceRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *ResponseToTripServiceRequest) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

type ResponseToTripServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseToTripServiceResponse) Reset() {
	*x = ResponseToTripServiceResponse{}
	mi := &file_pkg_pb_driver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseToTripServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseToTripServiceResponse) ProtoMessage() {}

func (x *ResponseToTripServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_driver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseToTripServiceResponse.ProtoReflect.Descriptor instead.
func (*ResponseToTripServiceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_driver_proto_rawDescGZIP(), []int{9}
}

func (x *ResponseToTripServiceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ResponseToTripServiceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_pb_driver_proto protoreflect.FileDescriptor

const file_pkg_pb_driver_proto_rawDesc = "" +
	"\n" +
	"\x13pkg/pb/driver.proto\x12\x06driver\"\xb2\x01\n" +
	"\x13CreateDriverRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\avehicle\x18\x02 \x01(\tR\avehicle\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12%\n" +
	"\x0elicense_number\x18\x06 \x01(\tR\rlicenseNumber\"\x98\x01\n" +
	"\x14CreateDriverResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\avehicle\x18\x05 \x01(\tR\avehicle\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\"g\n" +
	"\x1bUpdateDriverLocationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\"P\n" +
	"\x1cUpdateDriverLocationResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x95\x01\n" +
	"\"GetAvailableDriversNearUserRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1d\n" +
	"\n" +
	"max_driver\x18\x03 \x01(\x05R\tmaxDriver\x12\x16\n" +
	"\x06radius\x18\x04 \x01(\x05R\x06radius\"W\n" +
	"#GetAvailableDriversNearUserResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\adrivers\x18\x02 \x03(\x03R\adrivers\"\xa3\x02\n" +
	"\x1fSendNotificationToDriverRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12'\n" +
	"\x0fpickup_latitude\x18\x02 \x01(\x01R\x0epickupLatitude\x12)\n" +
	"\x10pickup_longitude\x18\x03 \x01(\x01R\x0fpickupLongitude\x12)\n" +
	"\x10dropoff_latitude\x18\x04 \x01(\x01R\x0fdropoffLatitude\x12+\n" +
	"\x11dropoff_longitude\x18\x05 \x01(\x01R\x10dropoffLongitude\x12\x1a\n" +
	"\bdistance\x18\x06 \x01(\x01R\bdistance\x12\x1b\n" +
	"\ttrip_fare\x18\a \x01(\x03R\btripFare\"T\n" +
	" SendNotificationToDriverResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"l\n" +
	"\x1cResponseToTripServiceRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\x03R\x06tripId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\x03R\bdriverId\x12\x16\n" +
	"\x06accept\x18\x03 \x01(\bR\x06accept\"Q\n" +
	"\x1dResponseToTripServiceResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x8a\x04\n" +
	"\rDriverService\x12I\n" +
	"\fCreateDriver\x12\x1b.driver.CreateDriverRequest\x1a\x1c.driver.CreateDriverResponse\x12a\n" +
	"\x14UpdateDriverLocation\x12#.driver.UpdateDriverLocationRequest\x1a$.driver.UpdateDriverLocationResponse\x12v\n" +
	"\x1bGetAvailableDriversNearUser\x12*.driver.GetAvailableDriversNearUserRequest\x1a+.driver.GetAvailableDriversNearUserResponse\x12m\n" +
	"\x18SendNotificationToDriver\x12'.driver.SendNotificationToDriverRequest\x1a(.driver.SendNotificationToDriverResponse\x12d\n" +
	"\x15ResponseToTripService\x12$.driver.ResponseToTripServiceRequest\x1a%.driver.ResponseToTripServiceResponseB\n" +
	"Z\b./pkg/pbb\x06proto3"

var (
	file_pkg_pb_driver_proto_rawDescOnce sync.Once
	file_pkg_pb_driver_proto_rawDescData []byte
)

func file_pkg_pb_driver_proto_rawDescGZIP() []byte {
	file_pkg_pb_driver_proto_rawDescOnce.Do(func() {
		file_pkg_pb_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_driver_proto_rawDesc), len(file_pkg_pb_driver_proto_rawDesc)))
	})
	return file_pkg_pb_driver_proto_rawDescData
}

var file_pkg_pb_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_pb_driver_proto_goTypes = []any{
	(*CreateDriverRequest)(nil),                 // 0: driver.CreateDriverRequest
	(*CreateDriverResponse)(nil),                // 1: driver.CreateDriverResponse
	(*UpdateDriverLocationRequest)(nil),         // 2: driver.UpdateDriverLocationRequest
	(*UpdateDriverLocationResponse)(nil),        // 3: driver.UpdateDriverLocationResponse
	(*GetAvailableDriversNearUserRequest)(nil),  // 4: driver.GetAvailableDriversNearUserRequest
	(*GetAvailableDriversNearUserResponse)(nil), // 5: driver.GetAvailableDriversNearUserResponse
	(*SendNotificationToDriverRequest)(nil),     // 6: driver.SendNotificationToDriverRequest
	(*SendNotificationToDriverResponse)(nil),    // 7: driver.SendNotificationToDriverResponse
	(*ResponseToTripServiceRequest)(nil),        // 8: driver.ResponseToTripServiceRequest
	(*ResponseToTripServiceResponse)(nil),       // 9: driver.ResponseToTripServiceResponse
}
var file_pkg_pb_driver_proto_depIdxs = []int32{
	0, // 0: driver.DriverService.CreateDriver:input_type -> driver.CreateDriverRequest
	2, // 1: driver.DriverService.UpdateDriverLocation:input_type -> driver.UpdateDriverLocationRequest
	4, // 2: driver.DriverService.GetAvailableDriversNearUser:input_type -> driver.GetAvailableDriversNearUserRequest
	6, // 3: driver.DriverService.SendNotificationToDriver:input_type -> driver.SendNotificationToDriverRequest
	8, // 4: driver.DriverService.ResponseToTripService:input_type -> driver.ResponseToTripServiceRequest
	1, // 5: driver.DriverService.CreateDriver:output_type -> driver.CreateDriverResponse
	3, // 6: driver.DriverService.UpdateDriverLocation:output_type -> driver.UpdateDriverLocationResponse
	5, // 7: driver.DriverService.GetAvailableDriversNearUser:output_type -> driver.GetAvailableDriversNearUserResponse
	7, // 8: driver.DriverService.SendNotificationToDriver:output_type -> driver.SendNotificationToDriverResponse
	9, // 9: driver.DriverService.ResponseToTripService:output_type -> driver.ResponseToTripServiceResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_pb_driver_proto_init() }
func file_pkg_pb_driver_proto_init() {
	if File_pkg_pb_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_driver_proto_rawDesc), len(file_pkg_pb_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_driver_proto_goTypes,
		DependencyIndexes: file_pkg_pb_driver_proto_depIdxs,
		MessageInfos:      file_pkg_pb_driver_proto_msgTypes,
	}.Build()
	File_pkg_pb_driver_proto = out.File
	file_pkg_pb_driver_proto_goTypes = nil
	file_pkg_pb_driver_proto_depIdxs = nil
}
