// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: pkg/pb/trip.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateTripStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	TripId        int64                  `protobuf:"varint,2,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Response      string                 `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTripStatusRequest) Reset() {
	*x = UpdateTripStatusRequest{}
	mi := &file_pkg_pb_trip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTripStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTripStatusRequest) ProtoMessage() {}

func (x *UpdateTripStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_trip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTripStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTripStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_trip_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateTripStatusRequest) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *UpdateTripStatusRequest) GetTripId() int64 {
	if x != nil {
		return x.TripId
	}
	return 0
}

func (x *UpdateTripStatusRequest) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

type UpdateTripStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTripStatusResponse) Reset() {
	*x = UpdateTripStatusResponse{}
	mi := &file_pkg_pb_trip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTripStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTripStatusResponse) ProtoMessage() {}

func (x *UpdateTripStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_trip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTripStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateTripStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_trip_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateTripStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateTripStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_pb_trip_proto protoreflect.FileDescriptor

const file_pkg_pb_trip_proto_rawDesc = "" +
	"\n" +
	"\x11pkg/pb/trip.proto\x12\x04trip\"k\n" +
	"\x17UpdateTripStatusRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x17\n" +
	"\atrip_id\x18\x02 \x01(\x03R\x06tripId\x12\x1a\n" +
	"\bresponse\x18\x03 \x01(\tR\bresponse\"L\n" +
	"\x18UpdateTripStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2`\n" +
	"\vTripService\x12Q\n" +
	"\x10UpdateTripStatus\x12\x1d.trip.UpdateTripStatusRequest\x1a\x1e.trip.UpdateTripStatusResponseB\n" +
	"Z\b./pkg/pbb\x06proto3"

var (
	file_pkg_pb_trip_proto_rawDescOnce sync.Once
	file_pkg_pb_trip_proto_rawDescData []byte
)

func file_pkg_pb_trip_proto_rawDescGZIP() []byte {
	file_pkg_pb_trip_proto_rawDescOnce.Do(func() {
		file_pkg_pb_trip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_pb_trip_proto_rawDesc), len(file_pkg_pb_trip_proto_rawDesc)))
	})
	return file_pkg_pb_trip_proto_rawDescData
}

var file_pkg_pb_trip_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_pb_trip_proto_goTypes = []any{
	(*UpdateTripStatusRequest)(nil),  // 0: trip.UpdateTripStatusRequest
	(*UpdateTripStatusResponse)(nil), // 1: trip.UpdateTripStatusResponse
}
var file_pkg_pb_trip_proto_depIdxs = []int32{
	0, // 0: trip.TripService.UpdateTripStatus:input_type -> trip.UpdateTripStatusRequest
	1, // 1: trip.TripService.UpdateTripStatus:output_type -> trip.UpdateTripStatusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_pb_trip_proto_init() }
func file_pkg_pb_trip_proto_init() {
	if File_pkg_pb_trip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_pb_trip_proto_rawDesc), len(file_pkg_pb_trip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_trip_proto_goTypes,
		DependencyIndexes: file_pkg_pb_trip_proto_depIdxs,
		MessageInfos:      file_pkg_pb_trip_proto_msgTypes,
	}.Build()
	File_pkg_pb_trip_proto = out.File
	file_pkg_pb_trip_proto_goTypes = nil
	file_pkg_pb_trip_proto_depIdxs = nil
}
