services:
  database:
    image: mysql:5.7
    container_name: notes-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notesdb
      MYSQL_USER: notesuser
      MYSQL_PASSWORD: notespass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"
    restart: always

volumes:
  db_data: